Repository Atos20/Rancid-Tomatillos, pull requests merged in 2020-10, with the labels that each got.

#20 Feature/add login form
  .vscode/settings.json
  package-lock.json
  package.json
  public/index.html
  src/App/App.css
  src/App/App.js
  src/App/App.scss
  src/LoginForm/LoginForm.js
  src/LoginForm/LoginForm.scss
  src/index.js
  src/index.scss
Labels: File organization, React component class, iteration 1

#21 Feature/homepage
  public/index.html
  src/App/App.css
  src/App/App.js
  src/Homepage/Homepage.scss
Labels: File organization, React component class, enhancement, functional component, iteration 1, styling

#23 Feature/add nav bar
  public/index.html
  src/App/App.css
  src/App/App.js
  src/Homepage/Homepage.js
  src/Homepage/Homepage.scss
  src/LoginForm/LoginForm.scss
Labels: iteration 1

#25 Fix untracked file
  src/Homepage/Homepage.js
Labels: bug

#27 Feature/add welcome status section
  public/index.html
  src/App/App.js
  src/WelcomingSection/WelcomingSection.js
  src/WelcomingSection/WelcomingSection.scss
  src/WelcomingSection/WelcomingSection.test.js
Labels: functional component, iteration 2

#31 Feature/fetch object
  src/API/APIcalls.js
Labels: API, enhancement, iteration 1, iteration 2, iteration 3

#32 Feature/add cards component
  public/index.html
  src/App/App.js
  src/Cards/Cards.js
  src/Cards/Cards.scss
  src/Cards/Cards.test.js
  src/Homepage/Homepage.js
Labels: React component class, iteration 2

#33 Get and display all movie cards
  src/API/APIcalls.js
  src/Cards/Cards.js
  src/Homepage/Homepage.js
Labels: API, File organization, React component class, iteration 1

#35 Feature/switchpage
  src/App/App.js
  src/Homepage/Homepage.js
Labels: enhancement, iteration 2

#36 Feature/add login functionality
  src/API/APIcalls.js
  src/App/App.js
  src/App/App.scss
  src/Cards/Cards.js
  src/Homepage/Homepage.js
  src/LoginForm/LoginForm.js
  src/LoginForm/LoginForm.scss
  src/WelcomingSection/WelcomingSection.js
Labels: API, iteration 2

#38 Feature/create nav component
  src/Homepage/Homepage.js
  src/NavBar/NavBar.js
  src/NavBar/NavBar.scss
  src/NavBar/NavBar.test.js
Labels: File organization, functional component, iteration 1

#39 Feature/test
  package-lock.json
  package.json
  src/App/App.test.js
  src/Card/Card.js
  src/Card/Card.scss
  src/Card/Card.test.js
  src/Cards/Cards.js
  src/Cards/Cards.scss
  src/Cards/Cards.test.js
  src/LoginForm/LoginForm.js
  src/LoginForm/LoginForm.test.js
  src/WelcomingSection/WelcomingSection.test.js
Labels: documentation, testing

#41 Feature/implement react route
  package-lock.json
  package.json
  src/App/App.js
  src/Homepage/Homepage.js
  src/LoginForm/LoginForm.js
  src/LoginForm/LoginForm.scss
  src/NavBar/NavBar.js
  src/WelcomingSection/WelcomingSection.js
  src/index.js
Labels: Routing

#43 Feature/display movie details
  package-lock.json
  package.json
  src/API/APIcalls.js
  src/App/App.js
  src/Card/Card.js
  src/Cards/Cards.js
  src/Homepage/Homepage.js
  src/MoviePage/MovieCard/MovieCard.js
  src/MoviePage/MovieCard/MovieCard.scss
  src/MoviePage/MovieCard/MovieCard.test.js
  src/MoviePage/MovieHeader/MovieHeader.js
  src/MoviePage/MovieHeader/MovieHeader.scss
  src/MoviePage/MovieHeader/MovieHeader.test.js
  src/MoviePage/MoviePage.js
  src/MoviePage/MoviePage.scss
  src/MoviePage/MoviePage.test.js
  src/NavBar/NavBar.js
Labels: Routing, SCSS, functional component, iteration 3, styling

#49 Feature/error handling
  public/manifest.json
  src/API/APIcalls.js
  src/App/App.js
  src/Card/Card.js
  src/Card/Card.test.js
  src/Cards/Cards.js
  src/ErrorMessage/ErrorMessage.js
  src/ErrorMessage/ErrorMessage.scss
  src/LoginForm/LoginForm.js
  src/MoviePage/MovieCard/MovieCard.js
  src/MoviePage/MoviePage.js
  src/WelcomingSection/WelcomingSection.js
  src/index.js
Labels: Routing, enhancement

#52 Feature/sort movies by rating
  src/Cards/Cards.js
  src/Cards/Cards.scss
  src/LoginForm/LoginForm.js
  src/SortMovies/SortMovies.js
  src/SortMovies/SortMovies.scss
  src/SortMovies/SortMovies.test.js
Labels: SCSS, functional component, styling

#64 Feature/unit testing
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.test.js
  src/Cards/Cards.js
  src/ErrorMessage/ErrorMessage.test.js
  src/LoginForm/LoginForm.js
  src/LoginForm/LoginForm.test.js
  src/MoviePage/MovieCard/MovieCard.js
  src/MoviePage/MovieCard/MovieCard.test.js
  src/MoviePage/MovieHeader/MovieHeader.test.js
  src/MoviePage/MoviePage.test.js
  src/NavBar/NavBar.test.js
  src/SortMovies/SortMovies.js
  src/SortMovies/SortMovies.test.js
Labels: testing

#66 Feature/lift state up in cards
  src/App/App.js
  src/Cards/Cards.js
  src/ErrorBoundary/ErrorBoundary.js
  src/ErrorBoundary/ErrorBoundary.scss
  src/ErrorBoundary/ErrorBoundary.test.js
  src/ErrorMessage/ErrorMessage.js
  src/Homepage/Homepage.js
  src/LoginForm/LoginForm.js
  src/MoviePage/MoviePage.js
Labels: ⚙️ refactoring

#67 Feature/wrap card in link
  src/Card/Card.js
  src/Cards/Cards.scss
Labels: ⚙️ refactoring, 💩 bug

#70 Feature/get user ratings
  src/API/APIcalls.js
  src/App/App.js
  src/ErrorBoundary/ErrorBoundary.test.js
  src/ErrorMessage/ErrorMessage.test.js
Labels: enhancement, ⭐️ iteration 4, 🚠 API

#71 Feature/display user rating
  src/API/APIcalls.js
  src/App/App.js
  src/App/App.scss
  src/Card/Card.js
  src/Card/Card.scss
  src/Cards/Cards.js
  src/Cards/Cards.scss
  src/Homepage/Homepage.js
  src/WelcomingSection/WelcomingSection.js
Labels: ⭐️ iteration 4, 🎨 styling

#73 🔘 Add home button
  src/Homepage/Homepage.scss
  src/NavBar/NavBar.js
  src/NavBar/NavBar.scss
Labels: Routing, enhancement, 🎨 styling, 🛣 Router, 🦾 SCSS

#76 Feature/add/change user rating
  package-lock.json
  package.json
  src/API/APIcalls.js
  src/App/App.js
  src/MoviePage/MovieHeader/MovieHeader.js
  src/MoviePage/MoviePage.js
Labels: enhancement, functional component, ⭐️ iteration 4

#77 Feature/style movie card
  src/MoviePage/MovieCard/MovieCard.js
  src/MoviePage/MovieCard/MovieCard.scss
  src/MoviePage/MovieHeader/MovieHeader.scss
  src/MoviePage/MoviePage.js
  src/MoviePage/MoviePage.scss
Labels: 🎨 styling, 🦾 SCSS

#79 Feature/rating styles
  src/App/App.js
  src/LoginForm/LoginForm.js
  src/LoginForm/LoginForm.scss
  src/MoviePage/MovieHeader/MovieHeader.js
  src/MoviePage/MovieHeader/MovieHeader.scss
Labels: ⚙️ refactoring, 🎨 styling

#80 Bugfix/rating updating
  src/App/App.js
  src/Card/Card.js
  src/Cards/Cards.js
  src/MoviePage/MovieCard/MovieCard.js
  src/MoviePage/MovieHeader/MovieHeader.js
  src/MoviePage/MoviePage.js
Labels: ⭐️ iteration 4, 🚮 iteration 5

#82 Bugfix/homepage ratings
  src/App/App.js
Labels: 💩 bug

#84 Feature/app test
  package-lock.json
  package.json
  src/API/APIcalls.js
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.js
  src/Card/Card.test.js
  src/Cards/Cards.js
  src/Cards/Cards.test.js
  src/LoginForm/LoginForm.js
  src/LoginForm/LoginForm.test.js
  src/MoviePage/MovieCard/MovieCard.test.js
  src/MoviePage/MoviePage.js
  src/MoviePage/MoviePage.test.js
  src/SortMovies/SortMovies.js
  src/SortMovies/SortMovies.test.js
  src/WelcomingSection/WelcomingSection.test.js
Labels: testing

#85 Implement Type checking with React prop-types
  src/Card/Card.js
  src/Cards/Cards.js
  src/Homepage/Homepage.js
  src/LoginForm/LoginForm.js
  src/MoviePage/MovieCard/MovieCard.js
  src/MoviePage/MovieHeader/MovieHeader.js
  src/MoviePage/MovieHeader/MovieHeader.test.js
  src/MoviePage/MoviePage.js
  src/NavBar/NavBar.js
  src/SortMovies/SortMovies.js
  src/WelcomingSection/WelcomingSection.js
Labels: PropTypes, testing

#108 Feature/api favorites
  src/API/APIcalls.js
  src/App/App.js
  src/Card/Card.js
  src/Cards/Cards.js
  src/Homepage/Homepage.js
Labels: Iteration 7b, 🚠 API

#111 Feature/favorite button
  src/App/App.js
  src/Card/Card.js
  src/Cards/Cards.js
  src/Homepage/Homepage.js
  src/MoviePage/MovieHeader/MovieHeader.js
  src/MoviePage/MoviePage.js
Labels: Iteration 7b

#114 Feature/display each comment
  src/App/App.js
  src/Comment/Comment.js
  src/Comment/Comment.scss
  src/Comment/Comment.test.js
  src/Comments/Comments.js
  src/MoviePage/MoviePage.js
Labels: Back-End, Front-End, Iteration 7a - Commenting, functional component

#123 Feature/audit
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.js
  src/Comment/Comment.js
  src/Comments/Comments.js
  src/Homepage/Homepage.scss
  src/LoginForm/LoginForm.js
  src/LoginForm/LoginForm.scss
  src/MoviePage/MovieHeader/MovieHeader.js
  src/MoviePage/MoviePage.js
  src/SortMovies/SortMovies.js
  src/SortMovies/SortMovies.scss
Labels: documentation, ⚙️ refactoring

#124 Test/fix breaking test files
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.js
  src/Cards/Cards.js
  src/Cards/Cards.test.js
  src/Comment/Comment.js
  src/Comments/Comments.js
  src/Homepage/Homepage.js
  src/Homepage/Homepage.test.js
  src/MoviePage/MovieCard/MovieCard.js
  src/MoviePage/MovieCard/MovieCard.test.js
  src/SortMovies/SortMovies.js
  src/SortMovies/SortMovies.test.js
  src/WelcomingSection/WelcomingSection.js
  src/WelcomingSection/WelcomingSection.test.js
Labels: testing, ⚙️ refactoring

#126 Feature/readme
  README.md
  readmeIMGs/homepage1.png
  readmeIMGs/homepage2.png
  readmeIMGs/login.png
  readmeIMGs/moviepage1.png
  readmeIMGs/moviepage2.png
  src/App/App.js
  src/Card/Card.js
  src/Cards/Cards.js
  src/Comment/Comment.js
  src/Comment/Comment.scss
  src/Comments/Comments.js
  src/ErrorBoundary/ErrorBoundary.js
  src/LoginForm/LoginForm.js
  src/MoviePage/MovieHeader/MovieHeader.js
  src/MoviePage/MoviePage.js
  src/SortMovies/SortMovies.js
Labels: PropTypes, documentation, ⚙️ refactoring, 💩 bug

#127 Feature/handling errors
  src/API/APIcalls.js
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.test.js
  src/LoginForm/LoginForm.js
  src/MoviePage/MoviePage.test.js
Labels: documentation, ⚙️ refactoring, 💩 bug

#128 Test/comments component
  src/App/App.test.js
  src/Comment/Comment.js
  src/Comment/Comment.scss
  src/Comments/Comments.js
  src/Comments/Comments.test.js
  src/Homepage/Homepage.test.js
  src/LoginForm/LoginForm.js
  src/LoginForm/LoginForm.test.js
  src/MoviePage/MoviePage.js
  src/MoviePage/MoviePage.test.js
Labels: testing

#129 Feature/cleanup bugs
  src/App/App.js
  src/App/App.test.js
  src/Comment/Comment.test.js
  src/LoginForm/LoginForm.js
  src/LoginForm/LoginForm.test.js
Labels: ⚙️ refactoring, 💩 bug

#130 Remove comments
  src/API/APIcalls.js
  src/App/App.js
  src/LoginForm/LoginForm.test.js
  src/MoviePage/MoviePage.js
Labels: ⚙️ refactoring
